//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbBookLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbBookLocation()
        {
            this.Stats = new HashSet<DbStats>();
        }
    
        public int Id { get; set; }
        public int Room { get; set; }
        public string Place { get; set; }
        public bool IsTaken { get; set; }
    
        public virtual DbPublication Publication { get; set; }
        public virtual DbReader Reader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbStats> Stats { get; set; }
    }
}
