//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbCourse
    {
        public int Id { get; set; }
        public bool C1 { get; set; }
        public bool C2 { get; set; }
        public bool C3 { get; set; }
        public bool C4 { get; set; }
    
        public virtual DbPublication Publication { get; set; }
    }
}
