//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBPublication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBPublication()
        {
            this.Reader = new HashSet<DBReader>();
            this.Writer = new HashSet<DBAuthor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DatePublished { get; set; }
        public string Publisher { get; set; }
        public byte Type { get; set; }
        public string PhysicalLocation { get; set; }
        public string InternetLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBReader> Reader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBAuthor> Writer { get; set; }
    }
}
