//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbReader
    {
        public int Id { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string Patronimic { get; set; }
        public byte AccessLevel { get; set; }
        public string Group { get; set; }
    
        public virtual DbBookLocation PhysicalLocation { get; set; }
    }
}
