//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Login { get; set; }
        public string Name { get; set; }
        public string Last { get; set; }
        public string Patronimic { get; set; }
        public byte AccessLevel { get; set; }
        public long PaswordHash { get; set; }
    }
}
